# Generated by Django 4.0.3 on 2022-04-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.CharField(choices=[('doing', 'DOING'), ('done', 'DONE')], max_length=5),
        ),
    ]
