# Generated by Django 4.0.3 on 2022-04-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updated_at_gt',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
