# Generated by Django 4.0.3 on 2022-05-02 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_updated_at_gt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updated_at_gt',
        ),
    ]
